#!/bash/bin
#~ OSM server install script
#~ OSM needs 5 main components: Mod_tile, renderd, mapnik, osm2pgsql, postgresql
#~ Manusal can be found on http://switch2osm.org

sudo cat "osm ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

#~ Installing dependencies

#Mapnik requires Boost 
sudo add-apt-repository ppa:mapnik/boost 
sudo apt-get -y update
sudo apt-get -y install libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-python-dev libboost-regex-dev libboost-system-dev libboost-thread-dev

#other packages
sudo apt-get -y install subversion git-core 
sudo apt-get -y install tar unzip wget bzip2

#unknown packages 207MB
sudo apt-get -y install build-essential autoconf libtool libxml2-dev libgeos-dev libpq-dev libbz2-dev proj munin-node munin libprotobuf-c0-dev protobuf-c-compiler libfreetype6-dev libpng12-dev libtiff4-dev libicu-dev libgdal-dev libcairo-dev libcairomm-1.0-dev

sudo apt-get -y install apache2 apache2-dev 
sudo apt-get -y install libagg-dev liblua5.2-dev ttf-unifont

#~ Installing database [postgresql]
sudo apt-get -y install postgresql-9.1-postgis postgresql-contrib postgresql-server-dev-9.1

sudo /etc/init.d/postgresql restart

# database is called gis by convention. Change 'osm' to your username in the two places below. This user will render maps with Mapnik.

sudo -u postgres createuser -s osm
sudo -u postgres createdb -E UTF8 -O osm gis

# ??? man psql -f -d  "Set up PostGIS on the postgresql database:"
psql -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql -d gis

# user 'osm' permission to access some of the PostGIS data 
psql -d gis -c "ALTER TABLE geometry_columns OWNER TO osm; ALTER TABLE spatial_ref_sys OWNER TO osm;"

#~ Installing osm2pgsql
mkdir ~/src
cd ~/src
git clone git://github.com/openstreetmap/osm2pgsql.git
cd osm2pgsql
./autogen.sh
./configure
make
sudo make install
psql -f /usr/local/share/osm2pgsql/900913.sql -d gis

#~ Install Mapnik Library
cd ~/src
git clone git://github.com/mapnik/mapnik
cd mapnik
git branch 2.0 origin/2.0.x
git checkout 2.0

python scons/scons.py configure INPUT_PLUGINS=all OPTIMIZATION=3 SYSTEM_FONTS=/usr/share/fonts/truetype/
python scons/scons.py
sudo python scons/scons.py install
sudo ldconfig

#~ Install mod_tile and renderd
cd ~/src
git clone git://github.com/openstreetmap/mod_tile.git
cd mod_tile
./autogen.sh
./configure
make
sudo make install
sudo make install-mod_tile
sudo ldconfig

#~ Install Mapnik styles
cd ~/src
svn co http://svn.openstreetmap.org/applications/rendering/mapnik mapnik-style

# Coastline data over 400MB downloads
cd ~/src/mapnik-style
#sudo ./get-coastlines.sh /usr/local/share

cd inc
cp fontset-settings.xml.inc.template fontset-settings.xml.inc
cp datasource-settings.xml.inc.template datasource-settings.xml.inc
cp settings.xml.inc.template settings.xml.inc

#MODIFY!
#______

#~ Configure renderd
#/usr/local/etc/renderd.conf

#socketname=/var/run/renderd/renderd.sock
#plugins_dir=/usr/local/lib/mapnik/input
#font_dir=/usr/share/fonts/truetype/ttf-dejavu
#XML=/home/osm/src/mapnik-style/osm.xml
#HOST=localhost

#files required for the mod_tile system to run
sudo mkdir /var/run/renderd
sudo chown osm /var/run/renderd
sudo mkdir /var/lib/mod_tile
sudo chown osm /var/lib/mod_tile

#~ Configure mod_tile
sudo cat "LoadModule tile_module /usr/lib/apache2/modules/mod_tile.so" >> /etc/apache2/conf.d/mod_tile

#after admin email line in /etc/apache2/sites-available/default
# Change it!!!!!!
LoadTileConfigFile /usr/local/etc/renderd.conf
ModTileRenderdSocketName /var/run/renderd/renderd.sock
# Timeout before giving up for a tile to be rendered
ModTileRequestTimeout 0
# Timeout before giving up for a tile to be rendered that is otherwise missing
ModTileMissingRequestTimeout 30
